# Step 1: Build the app using Node.js
FROM node:22 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json to the container
COPY package*.json ./

# Create config dir

RUN mkdir /etc/home_cinema

# Install the dependencies
RUN npm install

# Copy the rest of the app code
COPY . .


# Expose the port that the app will run on
EXPOSE 5173

# Command to run Nginx
CMD ["npm", "run", "dev"]
